version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/var/www
    restart: unless-stopped

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www/
    working_dir: /var/www
    command: composer install

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud-produtos
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - db:db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mypassword

